### ISSUE TITLE
Support for wasm32-wasi

### ISSUE THREAD

**Issue by skyne98** [dcuddeback/libudev-rs#23]
Hey there!

I have tried to build libudev-rs for the wasm32-wasi target and it was successful. However, building an application using it as a dependency fails on a linking stage. It says that it `cannot find library: -ludev`.  I am using Ubuntu 18.04 (WSL) and have libudev1 and libudev-dev packages installed.

Thanks!

**Comment by dcuddeback** [comment]
@skyne98 I have no familiarity with `wasm32-wasi`. Your error message is suspicious. Since this library uses `pkg-config` to get the linker flags to link to libudev, the fact that you're getting to the linkage stage suggests that `pkg-config` ran successfully, but the flags it returned don't actually link you to the libudev library for whatever reason. Perhaps you're using the system `pkg-config` when compiling for a different target?

This suggests a configuration problem with your dev environment. I'm closing this ticket, because it doesn't seem like a bug in libudev-rs or libudev-sys. This library merely wraps a C library. You might look to the upstream package (the libudev C library) for documentation on how to build for unusual platforms.
