### ISSUE TITLE
Unable to store a MonitorSocket for later use

### ISSUE THREAD

**Issue by 4xrsJCr9** [dcuddeback/libudev-rs#3]
There does not seem to be any way to store a `MonitorSocket` along with the corresponding `Context` in a structure. 

This would be useful in the scenario where the underlying `fd` of the `MonitorSocket` is registered with an eventloop and a `struct` is used to store state used in the callback invoked by the eventloop.

**Comment by dcuddeback** [comment]
I think this is a limitation of the borrow checker, because it prevents structs from referencing their own members. I saw some discussion a while back about fixing it at the language level. I don't know if there's much that can be done to address it here. Given the silence on this ticket, I assume no one else has ideas on how to address this, either. Feel free to reopen if you have a suggestion.

**Comment by proton-decay** [comment]
Another approach to fix this issue. This one is better than my previous one as it also allows to send `MonitorSocket` between threads. Details in pull request.

**Comment by dcuddeback** [comment]
> I saw some discussion a while back about fixing it at the language level.

This was a long time ago, and I haven't heard much about self-borrows in a while, so I don't think we'll see this addressed at the language level any time soon. I'd like to reduce the lifetimes in this library to make it easier to use. I just reviewed a couple PRs, including @darkelement's, that implement `Clone` for `Context`. The problem with this approach is that `Context` is not threadsafe, as per libudev's documentation.

**Comment by dcuddeback** [comment]
The thread-safety issue actually isn't a problem, because the types are `!Send`. #13 should land soon.

**Comment by dcuddeback** [comment]
Fixed in #13, which is now released in v0.3.0: https://github.com/dcuddeback/libudev-rs/releases/tag/v0.3.0.
